[project]
name = "concurrent-neural-networks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.3.0",
    "numpy>=2.1.2",
    "pydantic>=2.9.2",
]
